//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurutw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int d_id { get; set; }
        public string d_activity { get; set; }
        public Nullable<float> d_discount { get; set; }
        public Nullable<System.DateTime> d_startdate { get; set; }
        public Nullable<System.DateTime> d_enddate { get; set; }
        public Nullable<int> c_id { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
