//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurutw.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int o_id { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }

        [Display(Name = "Receiver")]
        public string o_receiver { get; set; }

        [Display(Name = "Address")]
        public string o_address { get; set; }
        public Nullable<System.DateTime> o_delivedate { get; set; }
        public string o_status { get; set; }

        public Nullable<int> pay_id { get; set; }

        public Nullable<int> dw_id { get; set; }
        public Nullable<int> m_id { get; set; }
    
        public virtual Delive_Way Delive_Way { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
