//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurutw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int od_id { get; set; }
        public Nullable<int> od_quantity { get; set; }
        public Nullable<float> od_price { get; set; }
        public Nullable<float> od_discount { get; set; }
        public Nullable<int> o_id { get; set; }
        public Nullable<int> pd_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product_Detail Product_Detail { get; set; }
    }
}
